#!/bin/sh

set -e

# ksh alternatives
update-alternatives --remove ksh /usr/bin/zsh
update-alternatives --remove ksh /bin/zsh4

# Remove alternatives system for zsh in general
update-alternatives --remove zsh /bin/zsh5
update-alternatives --remove rzsh /bin/zsh5

case "$1" in
    (configure)
    ;;
    (abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;
    (*)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

#DEBHELPER#

exit 0
